### PR TITLE
Made Repairing use an @Inject instead of @Overwrite

### PR DESCRIPTION
**Pull request by CammiePone**
Hello, so the `@Overwrite` you were using for the Repairing enchant kinda borked up with Curios, so I made it work with an `@Inject` instead.

Please ignore my stupid commit message, I meant to type inject, but typed mixin instead.

### CODE REVIEW

**Comment by cbyrne** [comment]
Have you tested this to make sure it works?

**Comment by CammiePone** [comment]
I did, and it does repair

**Comment by cbyrne** [comment]
Awesome, thanks for the PR!

**Comment by CammiePone** [comment]
uhh hold off on that, I juts closed and reopened the workspace and it crashed for some reason

**Comment by CammiePone** [comment]
Yea now I'm getting this, and I never even touched those classes
image

**Comment by cbyrne** [comment]
Ah okay, might be my issue. I'll merge in around 5 minutes and see if I can reproduce the issue

**Comment by CammiePone** [comment]
Alright. Idk why that wasn't a problem before, but it is now for me.

**Pull request merged**
